// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_create_task', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit()
    })
    it('test_create_task', async function () {
        await driver.get('http://localhost:8080/')
        await driver.findElement(By.name('username')).click()
        await driver.findElement(By.name('username')).sendKeys('user')
        await driver.findElement(By.name('password')).click()
        await driver.findElement(By.name('password')).sendKeys('pass')
        await driver.findElement(By.css('.w3-btn')).click()
        await driver.findElement(By.css('.Projects:nth-child(3) .w3-btn')).click()
        await driver.findElement(By.id('onglet_tasks')).click()
        await driver.findElement(By.css('.w3-btn:nth-child(1)')).click()
        await driver.findElement(By.name('taskId')).click()
        await driver.findElement(By.name('taskId')).sendKeys('1')
        await driver.findElement(By.name('description')).click()
        await driver.findElement(By.name('description')).sendKeys('description')
        await driver.findElement(By.css('input:nth-child(11)')).click()
        await driver.findElement(By.css('.w3-btn:nth-child(17)')).click()
    })
})
