// Generated by Selenium IDE
const webdriver = require('selenium-webdriver')
const By = webdriver.By
const chrome = require('selenium-webdriver/chrome')
const chromedriver = require('chromedriver')

chrome.setDefaultService(new chrome.ServiceBuilder(chromedriver.path).build())

const assert = require('assert')

describe('US1_CreateAccount', function () {
    this.timeout(30000)
    let driver
    beforeEach(async function () {
        driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build()
    })
    afterEach(async function () {
        await driver.quit()
    })
    it('US1_CreateAccount', async function () {
        await driver.get('http://localhost:8080/')
        await driver.manage().window().setRect(1920, 1128)
        await driver.findElement(By.linkText('Create an account')).click()
        await driver.findElement(By.name('email')).click()
        await driver.findElement(By.name('email')).sendKeys('mailTest@test.mail')
        await driver.findElement(By.name('username')).sendKeys('userTest')
        await driver.findElement(By.name('password')).sendKeys('userPass')
        await driver.findElement(By.css('.w3-btn')).click()
    })
})
